language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

before_script:
    - composer self-update
    - composer install --dev

script: 
    - cp phpunit.xml.dist phpunit.xml
    - vendor/bin/phpunit -c phpunit.xml --coverage-clover clover
